project:
  type: website

website:
  title: "Quantitative methods II" 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Sessions
      - menu:
          - text: "Session 1: OLS"
            href: sessions/session1.qmd
          - text: "Session 2: Logistic regressions"
            href: sessions/session2.qmd
          - text: "Session 3: Multinomial regressions"
            href: sessions/session3.qmd
          - text: "Session 4: Difference-in-Differences (DiD)"
            href: sessions/session4.qmd
          - text: "Session 5: Regression Discontinuity Design (RDD) and Instrumental Variables"
            href: sessions/session5.qmd
          - text: "Session 6: Time Series"
            href: sessions/session6.qmd
      - text: Exercices
      - menu:
          - text: "Exercices 1: OLS"
            href: exercices/exercices1.qmd
          - text: "Exercices 2: Logistic regressions"
            href: exercices/exercices2.qmd
          - text: "Exercices 3: Multinomial regressions"
            href: exercices/exercices3.qmd
          - text: "Exercices 4: Difference-in-Differences (DiD)"
            href: exercices/exercices4.qmd
          - text: "Exercices 5: Regression Discontinuity Design (RDD) and Instrumental Variables"
            href: exercices/exercices5.qmd
          - text: "Exercices 6: Time Series"
            href: exercices/exercices6.qmd
       
      - text: Homeworks
      - menu:
          - text: "Homework 1"
            href: homeworks/homework1.qmd
          - text: "Homework 2"
            href: homeworks/homework2.qmd
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    tabsets: true

